# 1. IMPORT AND EXPLORE DATASET

In [1]:
import pandas as pd

In [3]:
# Import dataset using Pandas
# Link to Dataset: https://www.kaggle.com/carrie1/ecommerce-data
# Data contains transactions details between 01/12/2010 and 09/12/2011 for a UK-based non-store online retail.
# The company specializes in selling unique gifts
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [4]:
# Let's view the types of data
# Note that InvoiceDate is in object format, we will need to convert it into Datetime format
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
# Convert Invoice date to datetime format
sales_df['InvoiceDate'] = pd.to_datetime(sales_df['InvoiceDate'])

In [8]:
# Check datatype again to confirm!
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [11]:
# Check the number of Null values in the data
sales_df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

**MINI CHALLENGE #1:**
- **How many unique countries are present in the dataset? List all countries**

In [14]:
sales_df['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [15]:
sales_df.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

# 2. GROUPBY

In [16]:
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [19]:
# A groupby operation involves some combination of splitting the object, applying a function, and combining the results.
# This can be used to group large amounts of data and compute operations on these groups.
# Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

sales_df.groupby('Country')['UnitPrice'].mean()

Country
Australia                 3.220612
Austria                   4.243192
Bahrain                   4.556316
Belgium                   3.644335
Brazil                    4.456250
Canada                    6.030331
Channel Islands           4.932124
Cyprus                    6.302363
Czech Republic            2.938333
Denmark                   3.256941
EIRE                      5.911077
European Community        4.820492
Finland                   5.448705
France                    5.028864
Germany                   3.966930
Greece                    4.885548
Hong Kong                42.505208
Iceland                   2.644011
Israel                    3.633131
Italy                     4.831121
Japan                     2.276145
Lebanon                   5.387556
Lithuania                 2.841143
Malta                     5.244173
Netherlands               2.738317
Norway                    6.012026
Poland                    4.170880
Portugal                  8.582976
RSA                       4.277586
Saudi Arabia              2.411000
Singapore               109.645808
Spain                     4.987544
Sweden                    3.910887
Switzerland               3.403442
USA                       2.216426
United Arab Emirates      3.380735
United Kingdom            4.532422
Unspecified               2.699574
Name: UnitPrice, dtype: float64

In [20]:
sales_df.groupby('Country')['UnitPrice'].min()

Country
Australia                   0.00
Austria                     0.12
Bahrain                     1.25
Belgium                     0.12
Brazil                      0.85
Canada                      0.10
Channel Islands             0.19
Cyprus                      0.12
Czech Republic              0.29
Denmark                     0.21
EIRE                        0.00
European Community          0.55
Finland                     0.12
France                      0.00
Germany                     0.00
Greece                      0.14
Hong Kong                   0.21
Iceland                     0.25
Israel                      0.06
Italy                       0.12
Japan                       0.21
Lebanon                     0.55
Lithuania                   1.25
Malta                       0.19
Netherlands                 0.00
Norway                      0.00
Poland                      0.19
Portugal                    0.12
RSA                         0.00
Saudi Arabia                0.42
Singapore                   0.19
Spain                       0.00
Sweden                      0.19
Switzerland                 0.00
USA                         0.42
United Arab Emirates        0.29
United Kingdom         -11062.06
Unspecified                 0.19
Name: UnitPrice, dtype: float64

In [21]:
sales_df.groupby('Country')['UnitPrice'].max()

Country
Australia                 350.00
Austria                    40.00
Bahrain                    12.75
Belgium                    39.95
Brazil                     10.95
Canada                    550.94
Channel Islands           293.00
Cyprus                    320.69
Czech Republic             40.00
Denmark                    18.00
EIRE                     1917.00
European Community         18.00
Finland                   275.60
France                   4161.06
Germany                   599.50
Greece                     50.00
Hong Kong                2653.95
Iceland                    12.75
Israel                    125.00
Italy                     300.00
Japan                      45.57
Lebanon                    14.95
Lithuania                   5.95
Malta                      65.00
Netherlands               206.40
Norway                    700.00
Poland                     40.00
Portugal                 1241.98
RSA                        14.95
Saudi Arabia                5.49
Singapore                3949.32
Spain                    1715.85
Sweden                     40.00
Switzerland                40.00
USA                        16.95
United Arab Emirates       37.50
United Kingdom          38970.00
Unspecified                16.95
Name: UnitPrice, dtype: float64

In [22]:
sales_df.groupby('InvoiceDate')['UnitPrice'].mean()

InvoiceDate
2010-12-01 08:26:00    3.910000
2010-12-01 08:28:00    1.850000
2010-12-01 08:34:00    4.833750
2010-12-01 08:35:00    5.950000
2010-12-01 08:45:00    2.764500
                         ...
2011-12-09 12:23:00    1.650000
2011-12-09 12:25:00    1.285000
2011-12-09 12:31:00    1.799048
2011-12-09 12:49:00    5.057500
2011-12-09 12:50:00    2.966667
Name: UnitPrice, Length: 23260, dtype: float64

In [23]:
sales_df.groupby(['Country', 'InvoiceDate'])['UnitPrice'].mean()

Country      InvoiceDate
Australia    2010-12-01 10:03:00    5.278571
             2010-12-08 09:53:00    2.726250
             2010-12-14 11:12:00    4.283333
             2010-12-17 14:10:00    3.510000
             2011-01-06 11:12:00    1.871304
                                      ...
Unspecified  2011-08-22 10:18:00    2.381429
             2011-08-22 13:32:00    8.115000
             2011-09-02 12:17:00    1.642879
             2011-11-16 10:18:00    2.339474
             2011-11-24 14:55:00    2.107353
Name: UnitPrice, Length: 23616, dtype: float64

**MINI CHALLENGE #2:**
- **What is the average, maximum and minimum prices on 2010-12-01 08:34:00**

In [35]:
# 2010-12-01 08:34:00의 평균 가격
sales_df.groupby('InvoiceDate')['UnitPrice'].mean()['2010-12-01 08:34:00']

4.83375

In [36]:
# 2010-12-01 08:34:00의 최대 가격
sales_df.groupby('InvoiceDate')['UnitPrice'].max()['2010-12-01 08:34:00']

9.95

In [37]:
# 2010-12-01 08:34:00의 최소 가격
sales_df.groupby('InvoiceDate')['UnitPrice'].min()['2010-12-01 08:34:00']

1.65

# 3. CREATE MULTI-INDEX DATAFRAME

In [52]:
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [53]:
# You can select any column to be the index for the DataFrame
# Use one column only as follows:
sales_df.set_index(keys=['InvoiceDate'], inplace=True)
sales_df

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
InvoiceDate,,,,,,,
12/1/2010 8:26,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom
12/1/2010 8:26,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom
12/1/2010 8:26,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom
12/1/2010 8:26,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom
12/1/2010 8:26,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...
12/9/2011 12:50,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France
12/9/2011 12:50,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France
12/9/2011 12:50,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France
12/9/2011 12:50,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France
12/9/2011 12:50,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France

In [54]:
# Let's see how many unique countries are present in the dataframe
sales_df['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [55]:
# Alternatively, We can have multiple keys (indexes) using Pandas Multi-indexing
# Take the columns with the least number of unique values and use it for the outermost index

# Let's import the dataset again using Pandas

sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df.set_index(keys=['Country', 'InvoiceDate'], inplace=True)

sales_df

                               InvoiceNo StockCode  \
Country        InvoiceDate
United Kingdom 12/1/2010 8:26     536365    85123A
               12/1/2010 8:26     536365     71053
               12/1/2010 8:26     536365    84406B
               12/1/2010 8:26     536365    84029G
               12/1/2010 8:26     536365    84029E
...                                  ...       ...
France         12/9/2011 12:50    581587     22613
               12/9/2011 12:50    581587     22899
               12/9/2011 12:50    581587     23254
               12/9/2011 12:50    581587     23255
               12/9/2011 12:50    581587     22138

                                                        Description  Quantity  \
Country        InvoiceDate
United Kingdom 12/1/2010 8:26    WHITE HANGING HEART T-LIGHT HOLDER         6
               12/1/2010 8:26                   WHITE METAL LANTERN         6
               12/1/2010 8:26        CREAM CUPID HEARTS COAT HANGER         8
               12/1/2010 8:26   KNITTED UNION FLAG HOT WATER BOTTLE         6
               12/1/2010 8:26        RED WOOLLY HOTTIE WHITE HEART.         6
...                                                             ...       ...
France         12/9/2011 12:50          PACK OF 20 SPACEBOY NAPKINS        12
               12/9/2011 12:50         CHILDREN'S APRON DOLLY GIRL          6
               12/9/2011 12:50        CHILDRENS CUTLERY DOLLY GIRL          4
               12/9/2011 12:50      CHILDRENS CUTLERY CIRCUS PARADE         4
               12/9/2011 12:50        BAKING SET 9 PIECE RETROSPOT          3

                                UnitPrice  CustomerID
Country        InvoiceDate
United Kingdom 12/1/2010 8:26        2.55     17850.0
               12/1/2010 8:26        3.39     17850.0
               12/1/2010 8:26        2.75     17850.0
               12/1/2010 8:26        3.39     17850.0
               12/1/2010 8:26        3.39     17850.0
...                                   ...         ...
France         12/9/2011 12:50       0.85     12680.0
               12/9/2011 12:50       2.10     12680.0
               12/9/2011 12:50       4.15     12680.0
               12/9/2011 12:50       4.15     12680.0
               12/9/2011 12:50       4.95     12680.0

[541909 rows x 6 columns]

In [56]:
# Sort countries to start with alphabetical order
sales_df.sort_index(inplace=True)
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Australia   1/10/2011 9:58    540557     22523
            1/11/2011 9:47    540700     21581
            1/11/2011 9:47    540700     22619
            1/11/2011 9:47    540700    84997B
            1/11/2011 9:47    540700     20727
...                              ...       ...
Unspecified 9/2/2011 12:17    565303     85227
            9/2/2011 12:17    565303     22138
            9/2/2011 12:17    565303     21889
            9/2/2011 12:17    565303     22550
            9/2/2011 12:17    565303     23127

                                                  Description  Quantity  \
Country     InvoiceDate
Australia   1/10/2011 9:58            CHILDS GARDEN FORK PINK        96
            1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
            1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
            1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
            1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
Unspecified 9/2/2011 12:17     SET OF 6 3D KIT CARDS FOR KIDS         4
            9/2/2011 12:17      BAKING SET 9 PIECE RETROSPOT          2
            9/2/2011 12:17             WOODEN BOX OF DOMINOES         5
            9/2/2011 12:17                   HOLIDAY FUN LUDO         2
            9/2/2011 12:17          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
Country     InvoiceDate
Australia   1/10/2011 9:58       0.85     12415.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       1.65     12393.0
...                               ...         ...
Unspecified 9/2/2011 12:17       0.85         NaN
            9/2/2011 12:17       4.95         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       3.75         NaN
            9/2/2011 12:17       4.95         NaN

[541909 rows x 6 columns]

In [57]:
# Now you need more than one index to access any element
sales_df.index

MultiIndex([(  'Australia', '1/10/2011 9:58'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            (  'Australia', '1/11/2011 9:47'),
            ...
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17'),
            ('Unspecified', '9/2/2011 12:17')],
           names=['Country', 'InvoiceDate'], length=541909)

In [58]:
sales_df.index.names

FrozenList(['Country', 'InvoiceDate'])

In [59]:
# Multiindex objects
type(sales_df.index)

pandas.core.indexes.multi.MultiIndex

In [60]:
# It gives out the datetime and the country as well
sales_df.index[0]

('Australia', '1/10/2011 9:58')

**MINI CHALLENGE #3:**
- **Sort the DataFrame in a descending order (countries and dates)**

In [61]:
sales_df.sort_index(inplace=True, ascending=False)
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Unspecified 9/2/2011 12:17    565303     22904
            9/2/2011 12:17    565303     21329
            9/2/2011 12:17    565303     21992
            9/2/2011 12:17    565303     20772
            9/2/2011 12:17    565303     23196
...                              ...       ...
Australia   1/11/2011 9:47    540700     21578
            1/11/2011 9:47    540700     21577
            1/11/2011 9:47    540700     22245
            1/11/2011 9:47    540700     22244
            1/10/2011 9:58    540557     22523

                                                 Description  Quantity  \
Country     InvoiceDate
Unspecified 9/2/2011 12:17         CALENDAR PAPER CUT DESIGN         1
            9/2/2011 12:17           DINOSAURS  WRITING SET          1
            9/2/2011 12:17    VINTAGE PAISLEY STATIONERY SET         1
            9/2/2011 12:17               GARDEN PATH JOURNAL         1
            9/2/2011 12:17     VINTAGE LEAF MAGNETIC NOTEPAD         1
...                                                      ...       ...
Australia   1/11/2011 9:47  WOODLAND DESIGN  COTTON TOTE BAG        12
            1/11/2011 9:47   SAVE THE PLANET COTTON TOTE BAG        12
            1/11/2011 9:47      HOOK, 1 HANGER ,MAGIC GARDEN        12
            1/11/2011 9:47        3 HOOK HANGER MAGIC GARDEN        12
            1/10/2011 9:58           CHILDS GARDEN FORK PINK        96

                            UnitPrice  CustomerID
Country     InvoiceDate
Unspecified 9/2/2011 12:17       2.95         NaN
            9/2/2011 12:17       1.65         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       2.55         NaN
            9/2/2011 12:17       1.45         NaN
...                               ...         ...
Australia   1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       0.85     12393.0
            1/11/2011 9:47       1.95     12393.0
            1/10/2011 9:58       0.85     12415.0

[541909 rows x 6 columns]

# 4. MULTI-INDEXING OPERATIONS - PART #1

In [62]:
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df.set_index(keys=['Country', 'InvoiceDate'], inplace=True)
sales_df

                               InvoiceNo StockCode  \
Country        InvoiceDate
United Kingdom 12/1/2010 8:26     536365    85123A
               12/1/2010 8:26     536365     71053
               12/1/2010 8:26     536365    84406B
               12/1/2010 8:26     536365    84029G
               12/1/2010 8:26     536365    84029E
...                                  ...       ...
France         12/9/2011 12:50    581587     22613
               12/9/2011 12:50    581587     22899
               12/9/2011 12:50    581587     23254
               12/9/2011 12:50    581587     23255
               12/9/2011 12:50    581587     22138

                                                        Description  Quantity  \
Country        InvoiceDate
United Kingdom 12/1/2010 8:26    WHITE HANGING HEART T-LIGHT HOLDER         6
               12/1/2010 8:26                   WHITE METAL LANTERN         6
               12/1/2010 8:26        CREAM CUPID HEARTS COAT HANGER         8
               12/1/2010 8:26   KNITTED UNION FLAG HOT WATER BOTTLE         6
               12/1/2010 8:26        RED WOOLLY HOTTIE WHITE HEART.         6
...                                                             ...       ...
France         12/9/2011 12:50          PACK OF 20 SPACEBOY NAPKINS        12
               12/9/2011 12:50         CHILDREN'S APRON DOLLY GIRL          6
               12/9/2011 12:50        CHILDRENS CUTLERY DOLLY GIRL          4
               12/9/2011 12:50      CHILDRENS CUTLERY CIRCUS PARADE         4
               12/9/2011 12:50        BAKING SET 9 PIECE RETROSPOT          3

                                UnitPrice  CustomerID
Country        InvoiceDate
United Kingdom 12/1/2010 8:26        2.55     17850.0
               12/1/2010 8:26        3.39     17850.0
               12/1/2010 8:26        2.75     17850.0
               12/1/2010 8:26        3.39     17850.0
               12/1/2010 8:26        3.39     17850.0
...                                   ...         ...
France         12/9/2011 12:50       0.85     12680.0
               12/9/2011 12:50       2.10     12680.0
               12/9/2011 12:50       4.15     12680.0
               12/9/2011 12:50       4.15     12680.0
               12/9/2011 12:50       4.95     12680.0

[541909 rows x 6 columns]

In [67]:
# Obtain the first level of indexing (countries)
sales_df.index.get_level_values(0)

Index(['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom',
       'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom',
       'United Kingdom', 'United Kingdom',
       ...
       'France', 'France', 'France', 'France', 'France', 'France', 'France',
       'France', 'France', 'France'],
      dtype='object', name='Country', length=541909)

In [68]:
# Obtain the second level of indexing (Dates)
sales_df.index.get_level_values(1)

Index(['12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26',
       '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:28',
       '12/1/2010 8:28', '12/1/2010 8:34',
       ...
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50'],
      dtype='object', name='InvoiceDate', length=541909)

In [70]:
# Alternatively, you can select the name of the column/index
sales_df.index.get_level_values('Country')

Index(['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom',
       'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom',
       'United Kingdom', 'United Kingdom',
       ...
       'France', 'France', 'France', 'France', 'France', 'France', 'France',
       'France', 'France', 'France'],
      dtype='object', name='Country', length=541909)

In [71]:
# Same here, you can select the name of the coulumn/index
sales_df.index.get_level_values('InvoiceDate')

Index(['12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26',
       '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:26', '12/1/2010 8:28',
       '12/1/2010 8:28', '12/1/2010 8:34',
       ...
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50', '12/9/2011 12:50', '12/9/2011 12:50',
       '12/9/2011 12:50'],
      dtype='object', name='InvoiceDate', length=541909)

In [72]:
# You can change the names of the DataFrame by invoking the set_names method
sales_df.index.set_names(names=['Transaction Date', 'Transaction Location'], inplace=True)
sales_df

                                      InvoiceNo StockCode  \
Transaction Date Transaction Location
United Kingdom   12/1/2010 8:26          536365    85123A
                 12/1/2010 8:26          536365     71053
                 12/1/2010 8:26          536365    84406B
                 12/1/2010 8:26          536365    84029G
                 12/1/2010 8:26          536365    84029E
...                                         ...       ...
France           12/9/2011 12:50         581587     22613
                 12/9/2011 12:50         581587     22899
                 12/9/2011 12:50         581587     23254
                 12/9/2011 12:50         581587     23255
                 12/9/2011 12:50         581587     22138

                                                               Description  \
Transaction Date Transaction Location
United Kingdom   12/1/2010 8:26         WHITE HANGING HEART T-LIGHT HOLDER
                 12/1/2010 8:26                        WHITE METAL LANTERN
                 12/1/2010 8:26             CREAM CUPID HEARTS COAT HANGER
                 12/1/2010 8:26        KNITTED UNION FLAG HOT WATER BOTTLE
                 12/1/2010 8:26             RED WOOLLY HOTTIE WHITE HEART.
...                                                                    ...
France           12/9/2011 12:50               PACK OF 20 SPACEBOY NAPKINS
                 12/9/2011 12:50              CHILDREN'S APRON DOLLY GIRL
                 12/9/2011 12:50             CHILDRENS CUTLERY DOLLY GIRL
                 12/9/2011 12:50           CHILDRENS CUTLERY CIRCUS PARADE
                 12/9/2011 12:50             BAKING SET 9 PIECE RETROSPOT

                                       Quantity  UnitPrice  CustomerID
Transaction Date Transaction Location
United Kingdom   12/1/2010 8:26               6       2.55     17850.0
                 12/1/2010 8:26               6       3.39     17850.0
                 12/1/2010 8:26               8       2.75     17850.0
                 12/1/2010 8:26               6       3.39     17850.0
                 12/1/2010 8:26               6       3.39     17850.0
...                                         ...        ...         ...
France           12/9/2011 12:50             12       0.85     12680.0
                 12/9/2011 12:50              6       2.10     12680.0
                 12/9/2011 12:50              4       4.15     12680.0
                 12/9/2011 12:50              4       4.15     12680.0
                 12/9/2011 12:50              3       4.95     12680.0

[541909 rows x 6 columns]

**MINI CHALLENGE #4:**
- **Use InvoiceDate and Country in order as the multi-index**
- **Change the name of both indexes to "Date" and "location"**

In [73]:
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df.set_index(keys=['InvoiceDate', 'Country'], inplace=True)
sales_df

                               InvoiceNo StockCode  \
InvoiceDate     Country
12/1/2010 8:26  United Kingdom    536365    85123A
                United Kingdom    536365     71053
                United Kingdom    536365    84406B
                United Kingdom    536365    84029G
                United Kingdom    536365    84029E
...                                  ...       ...
12/9/2011 12:50 France            581587     22613
                France            581587     22899
                France            581587     23254
                France            581587     23255
                France            581587     22138

                                                        Description  Quantity  \
InvoiceDate     Country
12/1/2010 8:26  United Kingdom   WHITE HANGING HEART T-LIGHT HOLDER         6
                United Kingdom                  WHITE METAL LANTERN         6
                United Kingdom       CREAM CUPID HEARTS COAT HANGER         8
                United Kingdom  KNITTED UNION FLAG HOT WATER BOTTLE         6
                United Kingdom       RED WOOLLY HOTTIE WHITE HEART.         6
...                                                             ...       ...
12/9/2011 12:50 France                  PACK OF 20 SPACEBOY NAPKINS        12
                France                 CHILDREN'S APRON DOLLY GIRL          6
                France                CHILDRENS CUTLERY DOLLY GIRL          4
                France              CHILDRENS CUTLERY CIRCUS PARADE         4
                France                BAKING SET 9 PIECE RETROSPOT          3

                                UnitPrice  CustomerID
InvoiceDate     Country
12/1/2010 8:26  United Kingdom       2.55     17850.0
                United Kingdom       3.39     17850.0
                United Kingdom       2.75     17850.0
                United Kingdom       3.39     17850.0
                United Kingdom       3.39     17850.0
...                                   ...         ...
12/9/2011 12:50 France               0.85     12680.0
                France               2.10     12680.0
                France               4.15     12680.0
                France               4.15     12680.0
                France               4.95     12680.0

[541909 rows x 6 columns]

In [74]:
sales_df.index.set_names(names=['Date', 'location'], inplace=True)
sales_df

                               InvoiceNo StockCode  \
Date            location
12/1/2010 8:26  United Kingdom    536365    85123A
                United Kingdom    536365     71053
                United Kingdom    536365    84406B
                United Kingdom    536365    84029G
                United Kingdom    536365    84029E
...                                  ...       ...
12/9/2011 12:50 France            581587     22613
                France            581587     22899
                France            581587     23254
                France            581587     23255
                France            581587     22138

                                                        Description  Quantity  \
Date            location
12/1/2010 8:26  United Kingdom   WHITE HANGING HEART T-LIGHT HOLDER         6
                United Kingdom                  WHITE METAL LANTERN         6
                United Kingdom       CREAM CUPID HEARTS COAT HANGER         8
                United Kingdom  KNITTED UNION FLAG HOT WATER BOTTLE         6
                United Kingdom       RED WOOLLY HOTTIE WHITE HEART.         6
...                                                             ...       ...
12/9/2011 12:50 France                  PACK OF 20 SPACEBOY NAPKINS        12
                France                 CHILDREN'S APRON DOLLY GIRL          6
                France                CHILDRENS CUTLERY DOLLY GIRL          4
                France              CHILDRENS CUTLERY CIRCUS PARADE         4
                France                BAKING SET 9 PIECE RETROSPOT          3

                                UnitPrice  CustomerID
Date            location
12/1/2010 8:26  United Kingdom       2.55     17850.0
                United Kingdom       3.39     17850.0
                United Kingdom       2.75     17850.0
                United Kingdom       3.39     17850.0
                United Kingdom       3.39     17850.0
...                                   ...         ...
12/9/2011 12:50 France               0.85     12680.0
                France               2.10     12680.0
                France               4.15     12680.0
                France               4.15     12680.0
                France               4.95     12680.0

[541909 rows x 6 columns]

# 5. MULTI-INDEXING OPERATIONS - PART #2

In [76]:
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df.set_index(keys=['Country', 'InvoiceDate'], inplace=True)

# Sort countries to start with alphabetical order
sales_df.sort_index(inplace=True)
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Australia   1/10/2011 9:58    540557     22523
            1/11/2011 9:47    540700     21581
            1/11/2011 9:47    540700     22619
            1/11/2011 9:47    540700    84997B
            1/11/2011 9:47    540700     20727
...                              ...       ...
Unspecified 9/2/2011 12:17    565303     85227
            9/2/2011 12:17    565303     22138
            9/2/2011 12:17    565303     21889
            9/2/2011 12:17    565303     22550
            9/2/2011 12:17    565303     23127

                                                  Description  Quantity  \
Country     InvoiceDate
Australia   1/10/2011 9:58            CHILDS GARDEN FORK PINK        96
            1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
            1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
            1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
            1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
Unspecified 9/2/2011 12:17     SET OF 6 3D KIT CARDS FOR KIDS         4
            9/2/2011 12:17      BAKING SET 9 PIECE RETROSPOT          2
            9/2/2011 12:17             WOODEN BOX OF DOMINOES         5
            9/2/2011 12:17                   HOLIDAY FUN LUDO         2
            9/2/2011 12:17          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
Country     InvoiceDate
Australia   1/10/2011 9:58       0.85     12415.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       1.65     12393.0
...                               ...         ...
Unspecified 9/2/2011 12:17       0.85         NaN
            9/2/2011 12:17       4.95         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       3.75         NaN
            9/2/2011 12:17       4.95         NaN

[541909 rows x 6 columns]

In [78]:
# you can use a multi-index reference to access specific elements
# Alternatively, you can use a column name instead
sales_df.loc['Australia', '1/11/2011 9:47']

                         InvoiceNo StockCode  \
Country   InvoiceDate
Australia 1/11/2011 9:47    540700     21581
          1/11/2011 9:47    540700     22619
          1/11/2011 9:47    540700    84997B
          1/11/2011 9:47    540700     20727
          1/11/2011 9:47    540700     20726
          1/11/2011 9:47    540700     22383
          1/11/2011 9:47    540700     21249
          1/11/2011 9:47    540700     22378
          1/11/2011 9:47    540700     22175
          1/11/2011 9:47    540700     22176
          1/11/2011 9:47    540700    84997C
          1/11/2011 9:47    540700     20728
          1/11/2011 9:47    540700     22382
          1/11/2011 9:47    540700     21915
          1/11/2011 9:47    540700     22549
          1/11/2011 9:47    540700     21578
          1/11/2011 9:47    540700     21577
          1/11/2011 9:47    540700     22245
          1/11/2011 9:47    540700     22244

                                                Description  Quantity  \
Country   InvoiceDate
Australia 1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
          1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
          1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
          1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
          1/11/2011 9:47                 LUNCH BAG WOODLAND        20
          1/11/2011 9:47            LUNCH BAG SUKI  DESIGN         10
          1/11/2011 9:47   WOODLAND  HEIGHT CHART STICKERS          6
          1/11/2011 9:47               WALL TIDY RETROSPOT         20
          1/11/2011 9:47                  PINK OWL SOFT TOY        12
          1/11/2011 9:47                  BLUE OWL SOFT TOY        12
          1/11/2011 9:47  BLUE 3 PIECE POLKADOT CUTLERY SET         6
          1/11/2011 9:47                LUNCH BAG CARS BLUE        20
          1/11/2011 9:47         LUNCH BAG SPACEBOY DESIGN         20
          1/11/2011 9:47             RED  HARMONICA IN BOX         12
          1/11/2011 9:47                   PICTURE DOMINOES        12
          1/11/2011 9:47   WOODLAND DESIGN  COTTON TOTE BAG        12
          1/11/2011 9:47    SAVE THE PLANET COTTON TOTE BAG        12
          1/11/2011 9:47       HOOK, 1 HANGER ,MAGIC GARDEN        12
          1/11/2011 9:47         3 HOOK HANGER MAGIC GARDEN        12

                          UnitPrice  CustomerID
Country   InvoiceDate
Australia 1/11/2011 9:47       2.25     12393.0
          1/11/2011 9:47       3.75     12393.0
          1/11/2011 9:47       3.75     12393.0
          1/11/2011 9:47       1.65     12393.0
          1/11/2011 9:47       1.65     12393.0
          1/11/2011 9:47       1.65     12393.0
          1/11/2011 9:47       2.95     12393.0
          1/11/2011 9:47       0.85     12393.0
          1/11/2011 9:47       2.95     12393.0
          1/11/2011 9:47       2.95     12393.0
          1/11/2011 9:47       3.75     12393.0
          1/11/2011 9:47       1.65     12393.0
          1/11/2011 9:47       1.65     12393.0
          1/11/2011 9:47       1.25     12393.0
          1/11/2011 9:47       1.45     12393.0
          1/11/2011 9:47       2.25     12393.0
          1/11/2011 9:47       2.25     12393.0
          1/11/2011 9:47       0.85     12393.0
          1/11/2011 9:47       1.95     12393.0

In [79]:
# feed index as a tuple (important to avoid confusion)
# first argument references rows and the second argument references a column
sales_df.loc[('Australia', '1/11/2011 9:47'), 'UnitPrice']

Country    InvoiceDate
Australia  1/11/2011 9:47    2.25
           1/11/2011 9:47    3.75
           1/11/2011 9:47    3.75
           1/11/2011 9:47    1.65
           1/11/2011 9:47    1.65
           1/11/2011 9:47    1.65
           1/11/2011 9:47    2.95
           1/11/2011 9:47    0.85
           1/11/2011 9:47    2.95
           1/11/2011 9:47    2.95
           1/11/2011 9:47    3.75
           1/11/2011 9:47    1.65
           1/11/2011 9:47    1.65
           1/11/2011 9:47    1.25
           1/11/2011 9:47    1.45
           1/11/2011 9:47    2.25
           1/11/2011 9:47    2.25
           1/11/2011 9:47    0.85
           1/11/2011 9:47    1.95
Name: UnitPrice, dtype: float64

In [80]:
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Australia   1/10/2011 9:58    540557     22523
            1/11/2011 9:47    540700     21581
            1/11/2011 9:47    540700     22619
            1/11/2011 9:47    540700    84997B
            1/11/2011 9:47    540700     20727
...                              ...       ...
Unspecified 9/2/2011 12:17    565303     85227
            9/2/2011 12:17    565303     22138
            9/2/2011 12:17    565303     21889
            9/2/2011 12:17    565303     22550
            9/2/2011 12:17    565303     23127

                                                  Description  Quantity  \
Country     InvoiceDate
Australia   1/10/2011 9:58            CHILDS GARDEN FORK PINK        96
            1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
            1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
            1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
            1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
Unspecified 9/2/2011 12:17     SET OF 6 3D KIT CARDS FOR KIDS         4
            9/2/2011 12:17      BAKING SET 9 PIECE RETROSPOT          2
            9/2/2011 12:17             WOODEN BOX OF DOMINOES         5
            9/2/2011 12:17                   HOLIDAY FUN LUDO         2
            9/2/2011 12:17          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
Country     InvoiceDate
Australia   1/10/2011 9:58       0.85     12415.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       1.65     12393.0
...                               ...         ...
Unspecified 9/2/2011 12:17       0.85         NaN
            9/2/2011 12:17       4.95         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       3.75         NaN
            9/2/2011 12:17       4.95         NaN

[541909 rows x 6 columns]

In [81]:
# no issues with numeric indexing, you can use one index so no tuples are required
sales_df.iloc[0]

InvoiceNo                       540557
StockCode                        22523
Description    CHILDS GARDEN FORK PINK
Quantity                            96
UnitPrice                         0.85
CustomerID                     12415.0
Name: (Australia, 1/10/2011 9:58), dtype: object

In [82]:
# no issues with numeric indexing
sales_df.iloc[0, 0]

'540557'

In [89]:
# You can use transpose to Transpose indexes and columns
# reflect the DataFrame over its main diagonal by writing rows as columns and vice-versa.

sales_df = sales_df.transpose()
sales_df.head(10)

Country                    Australia                                   \
InvoiceDate           1/10/2011 9:58                   1/11/2011 9:47
InvoiceNo                     540557                           540700
StockCode                      22523                            21581
Description  CHILDS GARDEN FORK PINK  SKULLS  DESIGN  COTTON TOTE BAG
Quantity                          96                                6
UnitPrice                       0.85                             2.25
CustomerID                   12415.0                          12393.0

Country                                                                    \
InvoiceDate             1/11/2011 9:47                     1/11/2011 9:47
InvoiceNo                       540700                             540700
StockCode                        22619                             84997B
Description  SET OF 6 SOLDIER SKITTLES  RED 3 PIECE RETROSPOT CUTLERY SET
Quantity                             8                                  6
UnitPrice                         3.75                               3.75
CustomerID                     12393.0                            12393.0

Country                                                   \
InvoiceDate           1/11/2011 9:47      1/11/2011 9:47
InvoiceNo                     540700              540700
StockCode                      20727               20726
Description  LUNCH BAG  BLACK SKULL.  LUNCH BAG WOODLAND
Quantity                          20                  20
UnitPrice                       1.65                1.65
CustomerID                   12393.0             12393.0

Country                                                                 \
InvoiceDate           1/11/2011 9:47                    1/11/2011 9:47
InvoiceNo                     540700                            540700
StockCode                      22383                             21249
Description  LUNCH BAG SUKI  DESIGN   WOODLAND  HEIGHT CHART STICKERS
Quantity                          10                                 6
UnitPrice                       1.65                              2.95
CustomerID                   12393.0                           12393.0

Country                                               ...  \
InvoiceDate        1/11/2011 9:47     1/11/2011 9:47  ...
InvoiceNo                  540700             540700  ...
StockCode                   22378              22175  ...
Description  WALL TIDY RETROSPOT   PINK OWL SOFT TOY  ...
Quantity                       20                 12  ...
UnitPrice                    0.85               2.95  ...
CustomerID                12393.0            12393.0  ...

Country                             Unspecified                            \
InvoiceDate                      9/2/2011 12:17            9/2/2011 12:17
InvoiceNo                                565303                    565303
StockCode                                 20983                     20977
Description  12 PENCILS TALL TUBE RED RETROSPOT  36 PENCILS TUBE WOODLAND
Quantity                                      4                         4
UnitPrice                                  0.85                      1.25
CustomerID                                  NaN                       NaN

Country                                                       \
InvoiceDate               9/2/2011 12:17      9/2/2011 12:17
InvoiceNo                         565303              565303
StockCode                          20982               23084
Description  12 PENCILS TALL TUBE SKULLS  RABBIT NIGHT LIGHT
Quantity                               5                   1
UnitPrice                           0.85                2.08
CustomerID                           NaN                 NaN

Country                                                        \
InvoiceDate    9/2/2011 12:17                  9/2/2011 12:17
InvoiceNo              565303                          565303
StockCode               22549                           85227
Description  PICTURE DOMINOES  SET OF 6 3D KIT CARDS FOR KIDS
Quantity                    1                               4
UnitPrice                1.45                            0.85
CustomerID                NaN                             NaN

Country                                                             \
InvoiceDate                 9/2/2011 12:17          9/2/2011 12:17
InvoiceNo                           565303                  565303
StockCode                            22138                   21889
Description  BAKING SET 9 PIECE RETROSPOT   WOODEN BOX OF DOMINOES
Quantity                                 2                       5
UnitPrice                             4.95                    1.25
CustomerID                             NaN                     NaN

Country
InvoiceDate    9/2/2011 12:17             9/2/2011 12:17
InvoiceNo              565303                     565303
StockCode               22550                      23127
Description  HOLIDAY FUN LUDO  FELTCRAFT GIRL NICOLE KIT
Quantity                    2                          1
UnitPrice                3.75                       4.95
CustomerID                NaN                        NaN

[6 rows x 541909 columns]

In [90]:
sales_df.loc['UnitPrice', ('Australia', '1/10/2011 9:58')]

Country    InvoiceDate
Australia  1/10/2011 9:58    0.85
Name: UnitPrice, dtype: object

In [91]:
sales_df.loc['UnitPrice', ('Australia', '1/10/2011 9:58'):('Bellgium', '1/10/2011 9:58')]

Country    InvoiceDate
Australia  1/10/2011 9:58    0.85
           1/11/2011 9:47    2.25
           1/11/2011 9:47    3.75
           1/11/2011 9:47    3.75
           1/11/2011 9:47    1.65
                             ...
Belgium    9/9/2011 9:13     3.75
           9/9/2011 9:13     3.75
           9/9/2011 9:13     3.75
           9/9/2011 9:13      8.5
           9/9/2011 9:13     15.0
Name: UnitPrice, Length: 3748, dtype: object

In [96]:
# Let's import the dataset again using Pandas
sales_df = pd.read_csv('ecommerce_sales.csv', encoding='unicode_escape')
sales_df.set_index(keys=['Country', 'InvoiceDate'], inplace=True)

# Sort countries to start with alphabetical order
sales_df.sort_index(inplace=True)

In [97]:
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Australia   1/10/2011 9:58    540557     22523
            1/11/2011 9:47    540700     21581
            1/11/2011 9:47    540700     22619
            1/11/2011 9:47    540700    84997B
            1/11/2011 9:47    540700     20727
...                              ...       ...
Unspecified 9/2/2011 12:17    565303     85227
            9/2/2011 12:17    565303     22138
            9/2/2011 12:17    565303     21889
            9/2/2011 12:17    565303     22550
            9/2/2011 12:17    565303     23127

                                                  Description  Quantity  \
Country     InvoiceDate
Australia   1/10/2011 9:58            CHILDS GARDEN FORK PINK        96
            1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
            1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
            1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
            1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
Unspecified 9/2/2011 12:17     SET OF 6 3D KIT CARDS FOR KIDS         4
            9/2/2011 12:17      BAKING SET 9 PIECE RETROSPOT          2
            9/2/2011 12:17             WOODEN BOX OF DOMINOES         5
            9/2/2011 12:17                   HOLIDAY FUN LUDO         2
            9/2/2011 12:17          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
Country     InvoiceDate
Australia   1/10/2011 9:58       0.85     12415.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       1.65     12393.0
...                               ...         ...
Unspecified 9/2/2011 12:17       0.85         NaN
            9/2/2011 12:17       4.95         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       3.75         NaN
            9/2/2011 12:17       4.95         NaN

[541909 rows x 6 columns]

In [98]:
# You can perform swaplevel as follows:

sales_df = sales_df.swaplevel()
sales_df

                           InvoiceNo StockCode  \
InvoiceDate    Country
1/10/2011 9:58 Australia      540557     22523
1/11/2011 9:47 Australia      540700     21581
               Australia      540700     22619
               Australia      540700    84997B
               Australia      540700     20727
...                              ...       ...
9/2/2011 12:17 Unspecified    565303     85227
               Unspecified    565303     22138
               Unspecified    565303     21889
               Unspecified    565303     22550
               Unspecified    565303     23127

                                                  Description  Quantity  \
InvoiceDate    Country
1/10/2011 9:58 Australia              CHILDS GARDEN FORK PINK        96
1/11/2011 9:47 Australia      SKULLS  DESIGN  COTTON TOTE BAG         6
               Australia            SET OF 6 SOLDIER SKITTLES         8
               Australia    RED 3 PIECE RETROSPOT CUTLERY SET         6
               Australia              LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
9/2/2011 12:17 Unspecified     SET OF 6 3D KIT CARDS FOR KIDS         4
               Unspecified      BAKING SET 9 PIECE RETROSPOT          2
               Unspecified             WOODEN BOX OF DOMINOES         5
               Unspecified                   HOLIDAY FUN LUDO         2
               Unspecified          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
InvoiceDate    Country
1/10/2011 9:58 Australia         0.85     12415.0
1/11/2011 9:47 Australia         2.25     12393.0
               Australia         3.75     12393.0
               Australia         3.75     12393.0
               Australia         1.65     12393.0
...                               ...         ...
9/2/2011 12:17 Unspecified       0.85         NaN
               Unspecified       4.95         NaN
               Unspecified       1.25         NaN
               Unspecified       3.75         NaN
               Unspecified       4.95         NaN

[541909 rows x 6 columns]

In [99]:
# Perform swaplevel again:

sales_df = sales_df.swaplevel()
sales_df

                           InvoiceNo StockCode  \
Country     InvoiceDate
Australia   1/10/2011 9:58    540557     22523
            1/11/2011 9:47    540700     21581
            1/11/2011 9:47    540700     22619
            1/11/2011 9:47    540700    84997B
            1/11/2011 9:47    540700     20727
...                              ...       ...
Unspecified 9/2/2011 12:17    565303     85227
            9/2/2011 12:17    565303     22138
            9/2/2011 12:17    565303     21889
            9/2/2011 12:17    565303     22550
            9/2/2011 12:17    565303     23127

                                                  Description  Quantity  \
Country     InvoiceDate
Australia   1/10/2011 9:58            CHILDS GARDEN FORK PINK        96
            1/11/2011 9:47    SKULLS  DESIGN  COTTON TOTE BAG         6
            1/11/2011 9:47          SET OF 6 SOLDIER SKITTLES         8
            1/11/2011 9:47  RED 3 PIECE RETROSPOT CUTLERY SET         6
            1/11/2011 9:47            LUNCH BAG  BLACK SKULL.        20
...                                                       ...       ...
Unspecified 9/2/2011 12:17     SET OF 6 3D KIT CARDS FOR KIDS         4
            9/2/2011 12:17      BAKING SET 9 PIECE RETROSPOT          2
            9/2/2011 12:17             WOODEN BOX OF DOMINOES         5
            9/2/2011 12:17                   HOLIDAY FUN LUDO         2
            9/2/2011 12:17          FELTCRAFT GIRL NICOLE KIT         1

                            UnitPrice  CustomerID
Country     InvoiceDate
Australia   1/10/2011 9:58       0.85     12415.0
            1/11/2011 9:47       2.25     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       3.75     12393.0
            1/11/2011 9:47       1.65     12393.0
...                               ...         ...
Unspecified 9/2/2011 12:17       0.85         NaN
            9/2/2011 12:17       4.95         NaN
            9/2/2011 12:17       1.25         NaN
            9/2/2011 12:17       3.75         NaN
            9/2/2011 12:17       4.95         NaN

[541909 rows x 6 columns]

**MINI CHALLENGE #5:**
- **Calculate the average unit price for transactions occured in "United Kingdom" at "12/1/2010 8:26"**

In [101]:
sales_df.loc[('United Kingdom', '12/1/2010 8:26'), 'UnitPrice']

Country         InvoiceDate
United Kingdom  12/1/2010 8:26    2.55
                12/1/2010 8:26    3.39
                12/1/2010 8:26    2.75
                12/1/2010 8:26    3.39
                12/1/2010 8:26    3.39
                12/1/2010 8:26    7.65
                12/1/2010 8:26    4.25
Name: UnitPrice, dtype: float64

In [102]:
sales_df.loc[('United Kingdom', '12/1/2010 8:26'), 'UnitPrice'].mean()

3.91

# MINI CHALLENGE SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:**
- **How many unique countries are present in the dataset? List all countries**

In [ ]:
sales_df['Country'].unique()

In [ ]:
# Obtain the number of unique values in each column
sales_df.nunique()

**MINI CHALLENGE #2 SOLUTION:**
- **What is the average, maximum and minimum prices on 2010-12-01 08:34:00**

In [ ]:
# Min = 0.72 and Max = 1.85
sales_df.groupby('InvoiceDate')['UnitPrice'].min()

In [ ]:
sales_df.groupby('InvoiceDate')['UnitPrice'].max()

**MINI CHALLENGE #3 SOLUTION:**
- **Sort the DataFrame in a descending order (countries and dates)**

In [ ]:
# Please note that there is no point of adding [False, False] or [True, True]
sales_df.sort_index(ascending = False, inplace = True)
sales_df

**MINI CHALLENGE #4 SOLUTION:**
- **Use InvoiceDate and Country in order as the multi-index**
- **Change the name of both indexes to "Date" and "location"**

In [ ]:
sales_df = pd.read_csv('ecommerce_sales.csv', encoding = 'unicode_escape')
sales_df.set_index(keys = ["InvoiceDate", "Country"], inplace = True)
sales_df

In [ ]:
# You can change the names of the DataFrame by invoking the set_names method
sales_df.index.set_names(names = ['Date', 'Location'], inplace = True)
sales_df

**MINI CHALLENGE #5 SOLUTION:**
- **Calculate the average unit price for transactions occured in "United Kingdom" at "12/1/2010 8:26"**

In [ ]:
# Let's import the dataset again using Pandas
sales_df = pd.read_csv('ecommerce_sales.csv', encoding = 'unicode_escape')
sales_df.set_index(keys = ["Country", "InvoiceDate"], inplace = True)


print(sales_df.loc[("United Kingdom", "12/1/2010 8:26"), "UnitPrice"])

# feed index as a tuple (important to avoid confusion)
# first argument references rows and the second argument references a column
sales_df.loc[("United Kingdom", "12/1/2010 8:26"), "UnitPrice"].mean()