# 1. DEFINE A PANDAS DATAFRAME

In [1]:
import pandas as pd

In [2]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                               'Bank Client Name': ['AA', 'AB', 'BB', 'CD'],
                               'Net Worth [$]': [35000, 3000, 100000, 2000],
                               'Years with Bank': [4, 7, 10, 15]})

bank_client_df

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111               AA          35000                4
1             222               AB           3000                7
2             333               BB         100000               10
3             444               CD           2000               15

In [3]:
# Let's obtain the data type
print(type(bank_client_df))

<class 'pandas.core.frame.DataFrame'>

In [4]:
# you can only view the first couple of rows using .head()
bank_client_df.head(3)

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
0             111               AA          35000                4
1             222               AB           3000                7
2             333               BB         100000               10

In [5]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

   Bank Client ID Bank Client Name  Net Worth [$]  Years with Bank
2             333               BB         100000               10
3             444               CD           2000               15

In [6]:
# You can obtain the shape of the DataFrame (#rows, #columns)
bank_client_df.shape

(4, 4)

In [7]:
# Obtain DataFrame information
bank_client_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Bank Client ID    4 non-null      int64
 1   Bank Client Name  4 non-null      object
 2   Net Worth [$]     4 non-null      int64
 3   Years with Bank   4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes

**MINI CHALLENGE #1:**
- **A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)**
- **Calculate the total value of the porfolio including all stocks**

In [8]:
portfolio_df = pd.DataFrame({'stock ticker symbol':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40],
                             'Number of stocks':[3, 4, 9]})

portfolio_df

  stock ticker symbol  price per share [$]  Number of stocks
0                AAPL                 3500                 3
1                AMZN                  200                 4
2                   T                   40                 9

In [9]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']

stocks_dollar_value.sum()

11660

In [10]:
print('Total Portfolio Value = {}'.format(stocks_dollar_value.sum()))

Total Portfolio Value = 11660

# 2. INPUTS (READ CSV AND HTML DATA)

In [11]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')

In [12]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [13]:
# Read tabular data using read_html
house_prices_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [14]:
house_prices_df[0]

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %
8,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

In [15]:
house_prices_df[1]

,Province,Average House Price,12 Month Change
0,British Columbia,"$736,000",+ 7.6 %
1,Ontario,"$594,000",– 3.2 %
2,Alberta,"$353,000",– 7.5 %
3,Quebec,"$340,000",+ 7.6 %
4,Manitoba,"$295,000",– 1.4 %
5,Saskatchewan,"$271,000",– 3.8 %
6,Nova Scotia,"$266,000",+ 3.5 %
7,Prince Edward Island,"$243,000",+ 3.0 %
8,Newfoundland / Labrador,"$236,000",– 1.6 %
9,New Brunswick,"$183,000",– 2.2 %
10,Canadian Average,"$488,000",– 1.3 %
11,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

**MINI CHALLENGE #2:**
- **Write a code that uses Pandas to read tabular US retirement data**
- **You can use data from here: https://www.ssa.gov/oact/progdata/nra.html**

In [16]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

,Year of birth,Age
0,1937 and prior,65
1,1938,65 and 2 months
2,1939,65 and 4 months
3,1940,65 and 6 months
4,1941,65 and 8 months
5,1942,65 and 10 months
6,1943-54,66
7,1955,66 and 2 months
8,1956,66 and 4 months
9,1957,66 and 6 months
10,1958,66 and 8 months
11,1959,66 and 10 months
12,1960 and later,67
13,Notes: 1. Persons born on January 1 of any yea...,Notes: 1. Persons born on January 1 of any yea...

# 3. OUTPUTS (WRITE DATAFRAME INTO CSV)

In [17]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [18]:
# write to a csv file without an index
bank_df.to_csv('sample_output_index.csv', index=True)

**MINI CHALLENGE #3:**
- **Use set index = False and rerun the cell. Comment on the output CSV.**
- **Try to leverage the attribute compression and rerun the cell**

In [19]:
bank_df.to_csv('sample_output.csv', index=False)

In [20]:
bank_df.to_csv('sample_output.csv.gz', index=False, compression='gzip')

# 4. SETTING/RESETTING INDEX

In [21]:
# Pandas is used to read a csv file and store data in a DataFrame
# Note that a numeric index is being set by default
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [22]:
# You can assign a specific column to be the index as follows
bank_df.set_index('First Name', inplace=True)
bank_df

,Last Name,Email,Postal Code,Net Worth,Years with Bank
First Name,,,,,
Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [23]:
# You can go back and use numeric index using reset_index
bank_df.reset_index(inplace=True)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [24]:
# Alternatively, you can set the index name when you read the csv file as follows
bank_df = pd.read_csv('bank_client_information.csv', index_col='First Name')
bank_df

,Last Name,Email,Postal Code,Net Worth,Years with Bank
First Name,,,,,
Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

**MINI CHALLENGE #4:**
- **Load the bank_client_information.csv and then set the "Last Name" column as the index**

In [25]:
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

# 5. SELECTING COLUMNS FROM A DATAFRAME

In [26]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [27]:
# Return a column from the DataFrame
# Note that the output will be a Pandas Series (you can automatically tell by the lack of formating)
sample = bank_df['Email']
sample

0             bird@gmail.com
1         nsmall@hotmail.com
2            azikez@gahew.mr
3           chanel@gmail.com
4           kate@hotmail.com
5            samer@gmail.com
6    heba.ismail@hotmail.com
7        Laila.a@hotmail.com
8             daafeja@boh.jm
9          guutodi@bigwoc.kw
Name: Email, dtype: object

In [28]:
# Confirm the datatype of sample
print(type(sample))

<class 'pandas.core.series.Series'>

In [29]:
# Alternatively, you can use the following syntax to do the same
# Note that this method will not work if there are spaces in the column names
bank_df.Email

0             bird@gmail.com
1         nsmall@hotmail.com
2            azikez@gahew.mr
3           chanel@gmail.com
4           kate@hotmail.com
5            samer@gmail.com
6    heba.ismail@hotmail.com
7        Laila.a@hotmail.com
8             daafeja@boh.jm
9          guutodi@bigwoc.kw
Name: Email, dtype: object

In [30]:
# Since the column name has spaces, this will be the only way that will work!
bank_df['Net Worth']

0      5000.00
1     10000.00
2      9072.02
3     11072.02
4      5000.00
5    100000.00
6     50000.00
7     20000.00
8      2629.13
9      8626.96
Name: Net Worth, dtype: float64

In [31]:
# Let's select multiple columns from the DataFrame
# you need to define a list containing all column names that you would like to select
# Note that since we collected more than one column, the output is a DataFrame (Notice the rich formatting)
sample1 = bank_df[['First Name', 'Net Worth']]
sample1

  First Name  Net Worth
0      Bird     5000.00
1       Noah   10000.00
2       Nina    9072.02
3    Chanel    11072.02
4       Kate    5000.00
5      Samer  100000.00
6       Heba   50000.00
7      Laila   20000.00
8     Joseph    2629.13
9       Noah    8626.96

In [32]:
# Note that sample is now a DataFrame and not a Pandas Series (since it has multiple columns)
# You can use type to confirm or you can tell from the rich text formating
print(type(sample1))

<class 'pandas.core.frame.DataFrame'>

In [33]:
# Alternatively, you can define a list first and then use it to select columns
selected_columns = ['First Name', 'Net Worth']

sample2 = bank_df[selected_columns]
sample2

  First Name  Net Worth
0      Bird     5000.00
1       Noah   10000.00
2       Nina    9072.02
3    Chanel    11072.02
4       Kate    5000.00
5      Samer  100000.00
6       Heba   50000.00
7      Laila   20000.00
8     Joseph    2629.13
9       Noah    8626.96

In [34]:
# In order to access a given row in the dataframe
bank_df[0:2]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.0,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.0,6

**MINI CHALLENGE #5:**
- **Select the following columns from the dataFrame Net Worth, Years with Bank, and Postal Code**

In [35]:
bank_df[['Net Worth', 'Years with Bank', 'Postal Code']]

   Net Worth  Years with Bank Postal Code
0    5000.00                5     N94 3M0
1   10000.00                6     N8S 14K
2    9072.02                7     S1T 4E6
3   11072.02               10     N7T 3E6
4    5000.00               22     K8N 5H6
5  100000.00               26     J7H 3HY
6   50000.00               11     K8Y 3M8
7   20000.00                3     J8Y 3M0
8    2629.13                1     M6U 5U7
9    8626.96               13     K2D 4M9

# 6. ADDING/DELETING COLUMNS TO DATAFRAME

In [36]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [37]:
# Let's assume that we want to add a new column to the dataframe
bank_df['Age'] = [25, 26, 28, 30, 36, 22, 48, 55, 70, 69]

In [38]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Age
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,25
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,26
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,28
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,30
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,36
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,22
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,48
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,55
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,70
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,69

In [39]:
# You can also insert a new column in a given position
bank_df.insert(0, column='Credit Score', value=[600, 700, 750, 699, 550, 600, 750, 500, 520, 510])

In [40]:
bank_df

,Credit Score,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Age
0,600,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,25
1,700,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,26
2,750,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,28
3,699,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,30
4,550,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,36
5,600,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,22
6,750,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,48
7,500,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,55
8,520,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,70
9,510,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,69

In [41]:
# Delete a column from a DataFrame
del bank_df['Email']
bank_df

,Credit Score,First Name,Last Name,Postal Code,Net Worth,Years with Bank,Age
0,600,Bird,Steve,N94 3M0,5000.00,5,25
1,700,Noah,Small,N8S 14K,10000.00,6,26
2,750,Nina,Keller,S1T 4E6,9072.02,7,28
3,699,Chanel,Steve,N7T 3E6,11072.02,10,30
4,550,Kate,Noor,K8N 5H6,5000.00,22,36
5,600,Samer,Mo,J7H 3HY,100000.00,26,22
6,750,Heba,Ismail,K8Y 3M8,50000.00,11,48
7,500,Laila,Ahmed,J8Y 3M0,20000.00,3,55
8,520,Joseph,Patton,M6U 5U7,2629.13,1,70
9,510,Noah,Moran,K2D 4M9,8626.96,13,69

In [42]:
bank_df.drop(labels=['Last Name', 'Net Worth'], axis=1, inplace=True)

In [43]:
# Remove a column from a DataFrame and store it somehwere else using pop
Years_with_bank = bank_df.pop('Years with Bank')
Years_with_bank

0     5
1     6
2     7
3    10
4    22
5    26
6    11
7     3
8     1
9    13
Name: Years with Bank, dtype: int64

In [44]:
print(type(Years_with_bank))

<class 'pandas.core.series.Series'>

**MINI CHALLENGE #6:**
- **load the bank_client_information.csv file and perform the following: (assume any reasonable values)**
    - **Add a column indicating whether the client has a mortgage or not**
    - **Add a column indicating the value of mortage in dollars**

In [45]:
bank_df = pd.read_csv('bank_client_information.csv')

bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [46]:
bank_df.insert(5, column='Mortgage', value=[True, True, False, False, False, True, True, False, True, False])

bank_df.insert(6, column='value of Mortgage', value=[100, 120, 0, 0, 0, 200, 150, 0, 230, 0])

bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Mortgage,value of Mortgage,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,True,100,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,True,120,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,False,0,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,False,0,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,False,0,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,True,200,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,True,150,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,False,0,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,True,230,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,False,0,13

# 7. LABEL-BASED ELEMENTS SELECTION FROM A DATAFRAME ".LOC()"

In [47]:
# Load the csv file and set the last name as the index

bank_df = pd.read_csv('bank_client_information.csv', index_col='Last Name')
bank_df

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Steve,Bird,bird@gmail.com,N94 3M0,5000.00,5
Small,Noah,nsmall@hotmail.com,N8S 14K,10000.00,6
Keller,Nina,azikez@gahew.mr,S1T 4E6,9072.02,7
Steve,Chanel,chanel@gmail.com,N7T 3E6,11072.02,10
Noor,Kate,kate@hotmail.com,K8N 5H6,5000.00,22
Mo,Samer,samer@gmail.com,J7H 3HY,100000.00,26
Ismail,Heba,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Ahmed,Laila,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Patton,Joseph,daafeja@boh.jm,M6U 5U7,2629.13,1
Moran,Noah,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [48]:
# Sort the dataframe in an alphabetical order
bank_df.sort_index(inplace=True)

In [49]:
bank_df

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Ahmed,Laila,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Ismail,Heba,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Keller,Nina,azikez@gahew.mr,S1T 4E6,9072.02,7
Mo,Samer,samer@gmail.com,J7H 3HY,100000.00,26
Moran,Noah,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
Noor,Kate,kate@hotmail.com,K8N 5H6,5000.00,22
Patton,Joseph,daafeja@boh.jm,M6U 5U7,2629.13,1
Small,Noah,nsmall@hotmail.com,N8S 14K,10000.00,6
Steve,Bird,bird@gmail.com,N94 3M0,5000.00,5
Steve,Chanel,chanel@gmail.com,N7T 3E6,11072.02,10

In [50]:
# loc is used to filter rows and columns
# loc is label-based meaning you need to give a name of the rows (or columns) that you are interested in selecting
# Note that iloc is "integer index-based" meaning you can filter rows/columns by their integer index.
# Note that we obtained a Series because last name "Small" existed only once in the dataframe

bank_df.loc['Small']

First Name                       Noah
Email              nsmall@hotmail.com
Postal Code                   N8S 14K
Net Worth                     10000.0
Years with Bank                     6
Name: Small, dtype: object

In [51]:
# Note that you got a DataFrame back since Last Name 'Steve' existed more than one in the DataFrame
bank_df.loc['Steve']

          First Name             Email Postal Code  Net Worth  Years with Bank
Last Name
Steve          Bird     bird@gmail.com     N94 3M0    5000.00                5
Steve        Chanel   chanel@gmail.com     N7T 3E6   11072.02               10

In [52]:
# Note that you can select multiple rows using "colon :"
# Note that this is inclusive! meaning that "Ahmed" and "Patton" were selected in the output DataFrame
# Headsup: this will be different if we use integer based index such as iloc()

bank_df.loc['Ahmed':'Patton']

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Ahmed,Laila,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Ismail,Heba,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Keller,Nina,azikez@gahew.mr,S1T 4E6,9072.02,7
Mo,Samer,samer@gmail.com,J7H 3HY,100000.00,26
Moran,Noah,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
Noor,Kate,kate@hotmail.com,K8N 5H6,5000.00,22
Patton,Joseph,daafeja@boh.jm,M6U 5U7,2629.13,1

In [53]:
# Select all elements up to and including 'Keller' index
bank_df.loc[:'Keller']

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Ahmed,Laila,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Ismail,Heba,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Keller,Nina,azikez@gahew.mr,S1T 4E6,9072.02,7

In [54]:
# if you want to select multiple rows, you can pass them as a list as follows
bank_df.loc[['Keller', 'Steve', 'Mo']]

          First Name             Email Postal Code  Net Worth  Years with Bank
Last Name
Keller          Nina   azikez@gahew.mr     S1T 4E6    9072.02                7
Steve          Bird     bird@gmail.com     N94 3M0    5000.00                5
Steve        Chanel   chanel@gmail.com     N7T 3E6   11072.02               10
Mo             Samer   samer@gmail.com     J7H 3HY  100000.00               26

In [55]:
# You can also randomly select a fraction of the DataFrame
# Setting axis = 0 means rows, setting index = 1 means columns
bank_df.sample(n=5, axis=0)

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Mo,Samer,samer@gmail.com,J7H 3HY,100000.00,26
Moran,Noah,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
Steve,Chanel,chanel@gmail.com,N7T 3E6,11072.02,10
Keller,Nina,azikez@gahew.mr,S1T 4E6,9072.02,7
Patton,Joseph,daafeja@boh.jm,M6U 5U7,2629.13,1

In [56]:
# return a percentage (Ex: 30%) of the rows
bank_df.sample(frac=0.3, axis=0)

,First Name,Email,Postal Code,Net Worth,Years with Bank
Last Name,,,,,
Noor,Kate,kate@hotmail.com,K8N 5H6,5000.00,22
Moran,Noah,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
Steve,Chanel,chanel@gmail.com,N7T 3E6,11072.02,10

**MINI CHALLENGE #7:**
- **Load the csv data and use the "first name" column as the index**
- **Randomly select 2 rows from the DataFrame. Rerun the code and ensure that random rows are being selected**

In [57]:
bank_df = pd.read_csv('bank_client_information.csv', index_col='First Name')
bank_df

,Last Name,Email,Postal Code,Net Worth,Years with Bank
First Name,,,,,
Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [58]:
bank_df.sample(n=2, axis=0)

           Last Name             Email Postal Code  Net Worth  Years with Bank
First Name
Kate            Noor  kate@hotmail.com     K8N 5H6    5000.00               22
Nina          Keller   azikez@gahew.mr     S1T 4E6    9072.02                7

In [59]:
bank_df.sample(n=2, axis=0)

           Last Name             Email Postal Code  Net Worth  Years with Bank
First Name
Chanel         Steve  chanel@gmail.com     N7T 3E6   11072.02               10
Kate            Noor  kate@hotmail.com     K8N 5H6    5000.00               22

# 8. INTEGER INDEX-BASED ELEMENTS SELECTION FROM A DATAFRAME "iLOC()"

In [60]:
# Load the CSV file with default index
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [61]:
# You can access rows with their numeric index using iloc
bank_df.iloc[9]

First Name                      Noah
Last Name                      Moran
Email              guutodi@bigwoc.kw
Postal Code                  K2D 4M9
Net Worth                    8626.96
Years with Bank                   13
Name: 9, dtype: object

In [62]:
# You can access multiple rows with their numeric index using iloc and colon :
# Note that using iloc is exclusive, meaning that we did not include the last element (quite confusing I know!)
# We went from index = 2 up until and not including index 5 so index 2,3, and 4 are the one selected
bank_df.iloc[2:5]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22

In [63]:
# all up until and not including index 4
bank_df.iloc[:4]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10

In [64]:
# Multiple elements are selected using a list of indexes
bank_df.iloc[[2,4,9]]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [65]:
# Slicing a piece of the dataframe by selecting which row and column you would like to select
bank_df.iloc[4, 0:3]

First Name                Kate
Last Name                 Noor
Email         kate@hotmail.com
Name: 4, dtype: object

**MINI CHALLENGE #8:**
- **Write a code that selects the last two rows in the DataFrame using two different methods**

In [66]:
bank_df.iloc[8:10]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [67]:
bank_df.iloc[[8,9]]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [68]:
bank_df.iloc[-2:]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

# 9. BROADCASTING OPERATIONS & SETTING NEW DATAFRAME VALUES

In [80]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [81]:
# Let's assume that we want to update the networth of all our customers by $1000
bank_df['Net Worth'] = bank_df['Net Worth'] + 1000

In [82]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,6000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,11000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,10072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,12072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,6000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,101000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,51000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,21000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,3629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,9626.96,13

In [83]:
# Alternatively, you can add or subtract as follows
bank_df['Net Worth'] = bank_df['Net Worth'].add(1000)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,7000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,12000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,11072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,13072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,7000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,102000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,52000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,4629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,10626.96,13

In [84]:
# Let's convert from USD to CAD using the exchange rate 1 USD = 1.3 CAD
bank_df['Net Worth (CAD)'] = bank_df['Net Worth'].mul(1.3)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth (CAD)
0,Bird,Steve,bird@gmail.com,N94 3M0,7000.00,5,9100.000
1,Noah,Small,nsmall@hotmail.com,N8S 14K,12000.00,6,15600.000
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,11072.02,7,14393.626
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,13072.02,10,16993.626
4,Kate,Noor,kate@hotmail.com,K8N 5H6,7000.00,22,9100.000
5,Samer,Mo,samer@gmail.com,J7H 3HY,102000.00,26,132600.000
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,52000.00,11,67600.000
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.00,3,28600.000
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,4629.13,1,6017.869
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,10626.96,13,13815.048

In [85]:
# Decided to update the email address of a given customer
bank_df.iloc[4, 2] = 'kage.noor@gmail.com'

In [86]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth (CAD)
0,Bird,Steve,bird@gmail.com,N94 3M0,7000.00,5,9100.000
1,Noah,Small,nsmall@hotmail.com,N8S 14K,12000.00,6,15600.000
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,11072.02,7,14393.626
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,13072.02,10,16993.626
4,Kate,Noor,kage.noor@gmail.com,K8N 5H6,7000.00,22,9100.000
5,Samer,Mo,samer@gmail.com,J7H 3HY,102000.00,26,132600.000
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,52000.00,11,67600.000
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.00,3,28600.000
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,4629.13,1,6017.869
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,10626.96,13,13815.048

In [87]:
# Let's assume we want to update the networth of two clients
bank_df.iloc[[0,3], [4]] = [6000, 15000]

In [88]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth (CAD)
0,Bird,Steve,bird@gmail.com,N94 3M0,6000.00,5,9100.000
1,Noah,Small,nsmall@hotmail.com,N8S 14K,12000.00,6,15600.000
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,11072.02,7,14393.626
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,15000.00,10,16993.626
4,Kate,Noor,kage.noor@gmail.com,K8N 5H6,7000.00,22,9100.000
5,Samer,Mo,samer@gmail.com,J7H 3HY,102000.00,26,132600.000
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,52000.00,11,67600.000
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.00,3,28600.000
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,4629.13,1,6017.869
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,10626.96,13,13815.048

**MINI CHALLENGE #9:**
- **Let's assume that all clients in the bank has been investing their assets in a broad S&P500 ETF. The market has been performing really well and clients networth has increased by 12% annualy. Calculate the sum of all client's networth.**

In [89]:
bank_df['Net Worth'] = bank_df['Net Worth'].mul(1.12)

In [90]:
bank_df['Net Worth'].sum()

271407.4832

In [91]:
print('Total Networth of all cients = ${}'.format(bank_df['Net Worth'].sum()))

Total Networth of all cients = $271407.4832

# 10. SORTING AND ORDERING

In [92]:
# Let's read a CSV file using Pandas as follows
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [93]:
# You can sort the values in the dataframe according to number of years with bank
bank_df.sort_values(by='Years with Bank')

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26

In [94]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [98]:
# Set inplace = True to ensure that change has taken place in memory
bank_df.sort_values(by='Years with Bank', inplace=True)

In [99]:
# Note that now the change (ordering) took place
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26

In [101]:
# You can sort the values in a descending order as follows
# 내림차순 -> ascending=False
bank_df.sort_values(by='Years with Bank', ascending=False, inplace=True)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1

In [102]:
# You can sort the dataframe with index instead of values as follows
bank_df.sort_index(inplace=True)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [103]:
bank_df['Rank'] = bank_df['Net Worth'].rank(ascending=True).astype('int')

In [104]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Rank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,2
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,5
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,7
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,2
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,10
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,9
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,8
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,4

**MINI CHALLENGE #10:**
- **Sort customers by networth instead of years with bank. Make sure to update values in-memory.**

In [105]:
bank_df.sort_values(by='Net Worth', inplace=True)

In [106]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Rank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,1
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,2
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,2
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,4
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,6
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,7
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,8
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,9
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,10

# 11. PANDAS WITH FUNCTIONS

In [107]:
# Let's read a CSV file using Pandas as follows
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [108]:
# Define a function that increases all clients networth by a fixed value of 10% (for simplicity sake)
def networth_update(balance):
    return balance * 1.1

In [109]:
# You can apply a function to the DataFrame
bank_df['Net Worth'] = bank_df['Net Worth'].apply(networth_update)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5500.000,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,11000.000,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9979.222,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,12179.222,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5500.000,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,110000.000,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,55000.000,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.000,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2892.043,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,9489.656,13

In [111]:
bank_df['Name Length'] = bank_df['First Name'].apply(len)
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Name Length
0,Bird,Steve,bird@gmail.com,N94 3M0,5500.000,5,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,11000.000,6,4
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9979.222,7,4
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,12179.222,10,7
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5500.000,22,4
5,Samer,Mo,samer@gmail.com,J7H 3HY,110000.000,26,5
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,55000.000,11,4
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,22000.000,3,5
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2892.043,1,6
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,9489.656,13,4

**MINI CHALLENGE #11:**
- **Define a function that doubles an argument and adds $100**
- **Apply the function to the Net Worth Column in the DataFrame**
- **Calculate the updated total networth of all clients combined**

In [113]:
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [117]:
def update_networth2(value):
    return value * 2 +100

In [118]:
bank_df['new Networth'] = bank_df['Net Worth'].apply(update_networth2)

In [120]:
bank_df['new Networth']

0     10100.00
1     20100.00
2     18244.04
3     22244.04
4     10100.00
5    200100.00
6    100100.00
7     40100.00
8      5358.26
9     17353.92
Name: new Networth, dtype: float64

In [119]:
bank_df['new Networth'].sum()

443800.26

# 12. PANDAS OPERATIONS/FILTERING

In [121]:
# Let's read a CSV file using Pandas as follows
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [124]:
# Pick certain rows that satisfy a certain criteria
df_loyal = bank_df[(bank_df['Years with Bank'] >= 10)]
df_loyal

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [125]:
# Pick certain rows that satisfy 2 or more critirea

mask_1 = bank_df['Years with Bank'] >= 10
mask_2 = bank_df['Net Worth'] >= 50000

df_loyal = bank_df[mask_1 & mask_2]
df_loyal

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.0,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.0,11

In [126]:
# Pick certain rows that satisfy a certain criteria
df_filtered = bank_df[(bank_df['First Name'] == 'Heba')]
df_filtered

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.0,11

In [127]:
mask = bank_df['Last Name'].isin(['Steve', 'Mo'])
bank_df[mask]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26

In [128]:
# values that fall between a given range
bank_df[bank_df['Net Worth'].between(5000, 9000)]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [131]:
# Delete duplicated rows
bank_df['Last Name'].duplicated(keep=False)

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: Last Name, dtype: bool

In [133]:
# add a tilde symbol ~
mask = ~bank_df['Last Name'].duplicated(keep=False)
bank_df[mask]

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [137]:
# Let's read a CSV file using Pandas as follows
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

# Only One
# Drop duplicates
bank_df.drop_duplicates(subset=['Last Name'], inplace=True)

In [138]:
bank_df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [139]:
# We can also filter the Dataframe using the where method as follows
# Note that all rows that don't satisfy this critirea are set to NaN
bank_df = pd.read_csv('bank_client_information.csv')
mask = bank_df['Net Worth'] >= 20000

bank_df.where(mask)

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.0,26.0
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.0,11.0
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.0,3.0
8,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN

**MINI CHALLENGE #12:**
- **Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $15000**
- **What is the combined networth for all customers with 15000+ networth?**

In [141]:
bank_df = pd.read_csv('bank_client_information.csv')

df_high_networth = bank_df[(bank_df['Net Worth'] >= 15000)]
df_high_networth

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.0,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.0,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.0,3

In [142]:
df_high_networth['Net Worth'].sum()

170000.0

# 13. FEATURE ENGINEERING AND DEALING WITH MISSING DATASET

In [145]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [148]:
# first, let's locate rows that have Null values
employee_df.isnull()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1466,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1467,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1468,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1469,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [149]:
# first, let's locate rows that have Null values
employee_df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyIncome               3
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [150]:
# Drop any row that contains a Null value
# Note that the size of the dataframe has been reduced by 7 elements
# Note that all will be used to drop rows that contains only Null values
# Null 모두 삭제
employee_df.dropna(how='any', inplace=True)

In [152]:
# 7개의 Missing value drop
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8.0,...,3,80,0,8,2,2,7,7,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [154]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [158]:
# We can also indicate which columns we want to drop NaN from
employee_df.dropna(how='any', inplace=True, subset=['MonthlyIncome', 'PercentSalaryHike'])
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8.0,...,3,80,0,8,2,2,7,7,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [159]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [161]:
# Calculate the average monthly income
employee_df['MonthlyIncome'].mean()

6505.155419222904

In [163]:
# You can use Fillna to fill a given column with a certain value
employee_df['MonthlyIncome'].fillna(employee_df['MonthlyIncome'].mean(), inplace=True)

In [165]:
employee_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,...,1,80,0,6,3,4,4,3,1,2

In [168]:
employee_df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyIncome               0
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

**MINI CHALLENGE #13:**
- **Calculate the median monthly rate. Use the calculated median values to fill out missing data. Confirm that the process is successful**

In [170]:
employee_df = pd.read_csv('Human_Resources.csv')
employee_df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  1
DistanceFromHome            0
Education                   0
EducationField              1
EmployeeCount               0
EmployeeNumber              1
EnvironmentSatisfaction     0
Gender                      1
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     1
JobSatisfaction             0
MaritalStatus               1
MonthlyIncome               3
MonthlyRate                 2
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           1
PerformanceRating           1
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [171]:
employee_df['MonthlyIncome'].median()

4908.0

In [173]:
employee_df['MonthlyIncome'].fillna(4908.0, inplace=True)

<ipython-input-173-5b3fd52ee3d5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_df['MonthlyIncome'].fillna(4908.0, inplace=True)

# 14. CHANGE DATATYPES

In [174]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')

In [175]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1469 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1469 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1469 non-null   float64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1469 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1469 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1469 non-null   object
 18  MonthlyIncome             1467 non-null   float64
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(5), int64(21), object(9)
memory usage: 402.1+ KB

In [178]:
# Let's convert the hourly rate from int64 to float64
employee_df['HourlyRate'] = employee_df['HourlyRate'].astype('float64')
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1469 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1469 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1469 non-null   float64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1469 non-null   object
 12  HourlyRate                1470 non-null   float64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1469 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1469 non-null   object
 18  MonthlyIncome             1467 non-null   float64
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(6), int64(20), object(9)
memory usage: 402.1+ KB

In [180]:
# Since we have limited number of classes, we can use the categrory datatype
# check the memory usage with the info method to ensure that the size has been reduced
employee_df['PerformanceRating'] = employee_df['PerformanceRating'].astype('category')
employee_df['RelationshipSatisfaction'] = employee_df['RelationshipSatisfaction'].astype('category')

In [184]:
# Notice the reduction in size
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1469 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1469 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1469 non-null   float64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1469 non-null   object
 12  HourlyRate                1470 non-null   float64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1469 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1469 non-null   object
 18  MonthlyIncome             1467 non-null   float64
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   category
 25  RelationshipSatisfaction  1470 non-null   category
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: category(2), float64(5), int64(19), object(9)
memory usage: 382.3+ KB

**MINI CHALLENGE #14:**
- **Convert the BusinessTravel column to category format.**
- **How many KBytes in memory have been saved?**

In [185]:
employee_df['BusinessTravel'] = employee_df['BusinessTravel'].astype('category')
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   category
 3   DailyRate                 1470 non-null   int64
 4   Department                1469 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1469 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1469 non-null   float64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1469 non-null   object
 12  HourlyRate                1470 non-null   float64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1469 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1469 non-null   object
 18  MonthlyIncome             1467 non-null   float64
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   category
 25  RelationshipSatisfaction  1470 non-null   category
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: category(3), float64(5), int64(19), object(8)
memory usage: 372.4+ KB

# EXCELLENT JOB!

# MINI CHALLENGE SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:**
- **A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)**
- **Calculate the total value of the porfolio including all stocks**

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40],
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)

In [ ]:
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that uses Pandas to read tabular US retirement data**
- **You can use data from here: https://www.ssa.gov/oact/progdata/nra.html**

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

**MINI CHALLENGE #3 SOLUTION:**
- **Use set index = False and rerun the cell. Comment on the output CSV.**
- **Try to leverage the attribute compression and rerun the cell**

In [ ]:
# write to a csv file without an index
bank_df.to_csv('sample_output_noindex.csv', index = False)

In [ ]:
# write to a csv file with an index + gzip Compression
bank_df.to_csv('sample_output_noindex.csv.gz', index = False, compression = 'gzip')

**MINI CHALLENGE #4 SOLUTION:**
- **Load the bank_client_information.csv and then set the "Last Name" column as the index**

In [ ]:
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

In [ ]:
# You can assign a specific column to be the index as follows
bank_df.set_index("Last Name", inplace = True)
bank_df

**MINI CHALLENGE #5 SOLUTION:**
- **Select the following columns from the dataFrame Net Worth, Years with Bank, and Postal Code**

In [ ]:
my_selected_columns = ['Net Worth', 'Years with Bank', 'Postal Code']
sample = bank_df[my_selected_columns]
sample

**MINI CHALLENGE #6 SOLUTION:**
- **load the bank_client_information.csv file and perform the following: (assume any reasonable values)**
    - **Add a column indicating whether the client has a mortgage or not**
    - **Add a column indicating the value of mortage in dollars**

In [ ]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

# Let's assume that we want to add a new column to the dataframe
bank_df['Has Mortage'] = [1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
bank_df['Mortage Value'] = [200000, 130000, 0, 0, 0, 0, 400000, 0, 0, 0]
bank_df

**MINI CHALLENGE #7 SOLUTION:**
- **Load the csv data and use the "first name" column as the index**
- **Randomly select 2 rows from the DataFrame. Rerun the code and ensure that random rows are being selected**

In [ ]:
# Load the csv file and set the last name as the index
bank_df = pd.read_csv('bank_client_information.csv', index_col = 'First Name')
bank_df
# You can also randomly select a fraction of the DataFrame
# Setting axis = 0 means rows, setting index = 1 means columns
bank_df.sample(n = 2, axis = 0)

**MINI CHALLENGE #8 SOLUTION:**
- **Write a code that selects the last two rows in the DataFrame using two different methods**

In [ ]:
bank_df.iloc[8:]

In [ ]:
bank_df.iloc[-2:]

**MINI CHALLENGE #9 SOLUTION:**
- **Let's assume that all clients in the bank has been investing their assets in a broad S&P500 ETF. The market has been performing really well and clients networth has increased by 12% annualy. Calculate the sum of all client's networth.**

In [ ]:
# Pandas is used to read a csv file and store data in a DataFrame
bank_df = pd.read_csv('bank_client_information.csv')
bank_df

In [ ]:
# Let's convert from USD to CAD using the exchange rate 1 USD = 1.3 CAD
bank_df['Net Worth New'] = bank_df['Net Worth'].mul(1.12)
bank_df

In [ ]:
bank_df['Net Worth New'].sum()

In [ ]:
print("Total networth for all clients = ${}".format( bank_df['Net Worth New'].sum()))

**MINI CHALLENGE #10 SOLUTION:**
- **Sort customers by networth instead of years with bank. Make sure to update values in-memory.**

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_df.sort_values(by = 'Net Worth', inplace = True)
bank_df

**MINI CHALLENGE #11 SOLUTION:**
- **Define a function that doubles an argument and adds $100**
- **Apply the function to the Net Worth Column in the DataFrame**
- **Calculate the updated total networth of all clients combined**

In [ ]:
def networth_update(balance):
    return balance * 2 + 100 # assume that stock prices increased by 10%

In [ ]:
# You can apply a function to the DataFrame
results = bank_df['Net Worth'].apply(networth_update)
results

In [ ]:
results.sum()

**MINI CHALLENGE #12 SOLUTION:**
- **Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $15000**
- **What is the combined networth for all customers with 15000+ networth?**

In [ ]:
df_high_networth = bank_df[ (bank_df['Net Worth'] >= 15000) ]
df_high_networth

In [ ]:
df_high_networth['Net Worth'].sum()

**MINI CHALLENGE #13 SOLUTION:**
- **Calculate the median monthly rate. Use the calculated median values to fill out missing data. Confirm that the process is successful**

In [ ]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')
employee_df

In [ ]:
# first, let's locate rows that have Null values
employee_df.isnull().sum()

In [ ]:
# Calculate the average monthly income
employee_df['MonthlyRate'].median()

In [ ]:
# You can use Fillna to fill a given column with a certain value
employee_df['MonthlyRate'].fillna(employee_df['MonthlyRate'].median(), inplace = True)

In [ ]:
employee_df

In [ ]:
# first, let's locate rows that have Null values
employee_df.isnull().sum()

**MINI CHALLENGE #14 SOLUTION:**
- **Convert the BusinessTravel column to category format.**
- **How many KBytes in memory have been saved?**

In [ ]:
# Let's read a CSV file using Pandas as follows
employee_df = pd.read_csv('Human_Resources.csv')
employee_df.info()

In [ ]:
employee_df["BusinessTravel"] = employee_df['BusinessTravel'].astype("category")
employee_df.info()

In [ ]:
# 402.1+ KB vs. 392.1+ KB

**MINI CHALLENGE #6 SOLUTION:**
- **Let's assume that you became a new client to the bank**
- **Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.**
- **Add this new dataframe to the original dataframe "bank_df_all".**

In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'],
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

**MINI CHALLENGE #6 SOLUTION:**
- **Let's assume that you became a new client to the bank**
- **Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.**
- **Add this new dataframe to the original dataframe "bank_df_all".**

In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'],
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df